[workspace]
resolver = "2"
members = ["cli", "common", "server"]
# TODO: unpublish cli and common

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = { version = "0.12", features = ["json"] }
hey-cli-common = { path = "./common", version = "0.1.1" }
anyhow = "1.0"
nest_struct = "0.5"
strum_macros = "0.26"
strum = "0.26"
