[jobs.install]
command = ["cargo", "install", "--path", ".", "--color", "always"]
allow_warnings = true

[jobs.hey-1]
command = [
    "cargo",
    "run",
    "--color",
    "always",
    "--",
    "--shell",
    "fish",
    "reset changes in current branch",
]
background = false
need_stdout = true
allow_warnings = true
