[package]
name = "hey-cli-server"
version = "0.1.1"
edition = "2021"
publish = false

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
axum = "0.8.1"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
hey-cli-common = { workspace = true }
dotenv = "0.15"
async-openai = "0.26"
sentry = "0.35.0"
sentry-tracing = "0.35.0"
