[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: use .8 when it's released
axum = "=0.8.0-rc.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3.19"
