[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: use .8 when it's released
axum = "=0.8.0-rc.1"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
common = { path = "../common" }
dotenv = "0.15"
async-openai = "0.26"
