name: Build and Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # TODO: fix OpenSSL build on aarch64
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Install missing target
        run: rustup target add ${{ matrix.target }}
      - name: Build binary
        env:
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: cargo build --release --target ${{ matrix.target }} --manifest-path ./cli/Cargo.toml
      - name: Move to dist
        run: mkdir -p dist && mv ./target/${{ matrix.target }}/release/hey${{ matrix.os == 'windows-latest' && '.exe' || '' }} dist/hey-${{ matrix.target }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hey_cli-${{ matrix.target }}
          path: ./dist

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=$(grep '^version = ' cli/Cargo.toml | cut -d'"' -f2)" >> $GITHUB_OUTPUT
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/**
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          body: |
            Install on macOS or Linux:

            ```sh
            curl -fsSL http://hey_cli.zak-man.com/install.sh | sh
            ```

            Install on Windows:

            ```powershell
            irm http://hey_cli.zak-man.com/install.ps1 | iex
            ```
