name: Build and Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            "x86_64-pc-windows-msvc",
            "x86_64-apple-darwin",
            "aarch64-apple-darwin",
            "aarch64-unknown-linux-gnu",
            "x86_64-unknown-linux-gnu",
          ]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential unzip pkg-config libssl-dev curl openssh-client
      - name: Install missing target
        run: rustup target add ${{ matrix.target }}
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }} --manifest-path ./cli/Cargo.toml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hey_cli-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/hey_cli

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/**
